title: DevOps
description: This Repository consists information of DevOps Tools and Installation.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman


remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
